import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, AlertTriangle, ShieldAlert, Scale, Sparkles } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans pb-24 selection:bg-brand-100 selection:text-brand-900">
      {/* Soft Header */}
      <nav className="border-b border-slate-200/60 bg-white/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-6 h-20 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 group">
            <div className="p-2 rounded-lg group-hover:bg-slate-100 transition-colors">
              <ArrowLeft className="w-4 h-4 text-slate-400 group-hover:text-slate-900 transition-colors" />
            </div>
            <span className="text-sm font-bold text-slate-500 group-hover:text-slate-900 transition-colors">Back to Home</span>
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-brand-600 rounded-lg flex items-center justify-center shadow-sm shadow-brand-200">
              <FileText className="w-4.5 h-4.5 text-white" />
            </div>
            <span className="font-display font-bold text-xl tracking-tight text-slate-900">DOCURA</span>
          </div>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 pt-20">
        <header className="mb-16">
          <div className="inline-flex items-center gap-2 px-2.5 py-1 bg-amber-50 border border-amber-100 text-amber-700 text-[10px] font-bold rounded-full mb-6 uppercase tracking-widest">
            <AlertTriangle className="w-3 h-3" />
            Important Notice
          </div>
          <h1 className="font-display text-5xl font-bold tracking-tight text-slate-900 mb-4">Legal Disclaimer</h1>
          <p className="text-slate-500 font-medium">Last Updated: March 16, 2026</p>
        </header>

        <div className="space-y-12 text-slate-600 leading-relaxed font-medium">
          <div className="bg-amber-50 border border-amber-100 rounded-[2rem] p-10 space-y-4 shadow-sm">
            <div className="flex items-center gap-4 text-amber-800">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm">
                <Scale className="w-6 h-6" />
              </div>
              <h2 className="font-display text-2xl font-bold">Not Legal Advice</h2>
            </div>
            <p className="text-amber-900/80 font-bold text-lg leading-relaxed">
              DOCURA is not a law firm and does not provide legal advice. The information and analysis provided by our platform are for informational and educational purposes only.
            </p>
          </div>

          <section className="grid md:grid-cols-2 gap-8">
            <div className="bg-white p-8 rounded-3xl border border-slate-200/60 shadow-sm space-y-4">
              <div className="w-12 h-12 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-900">
                <ShieldAlert className="w-6 h-6" />
              </div>
              <h3 className="font-display text-xl font-bold text-slate-900">AI Accuracy Warning</h3>
              <p className="text-sm leading-relaxed">
                The analysis generated by DOCURA is produced by artificial intelligence. While we strive for accuracy, AI models can make mistakes, overlook critical details, or misinterpret complex legal language. You should never rely solely on AI-generated output for legal or business decisions.
              </p>
            </div>
            <div className="bg-white p-8 rounded-3xl border border-slate-200/60 shadow-sm space-y-4">
              <div className="w-12 h-12 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-900">
                <Scale className="w-6 h-6" />
              </div>
              <h3 className="font-display text-xl font-bold text-slate-900">No Attorney-Client Relationship</h3>
              <p className="text-sm leading-relaxed">
                Your use of DOCURA does not create an attorney-client relationship between you and DOCURA AI. No information provided through the Service is protected by attorney-client privilege or work product doctrine.
              </p>
            </div>
          </section>

          <section className="bg-white p-10 rounded-[2rem] border border-slate-200/60 shadow-sm space-y-6">
            <h2 className="font-display text-2xl font-bold text-slate-900">Independent Verification</h2>
            <p>
              Users must independently verify all information extracted or summarized by DOCURA before relying on it. You are responsible for reviewing the original document in its entirety. DOCURA does not guarantee the accuracy, completeness, or usefulness of any analysis provided.
            </p>
            <p className="p-6 bg-slate-50 rounded-2xl border border-slate-100 text-slate-500 italic">
              We strongly recommend that you consult with a qualified legal professional or subject matter expert before making any legal decisions, signing contracts, or taking actions based on the analysis provided by this platform.
            </p>
          </section>

          <section className="bg-rose-50 p-10 rounded-[2rem] border border-rose-100 shadow-sm space-y-6">
            <h2 className="font-display text-2xl font-bold text-rose-900">Limitation of Warranty</h2>
            <p className="text-rose-700 font-bold">
              DOCURA DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WE ARE NOT RESPONSIBLE FOR ANY LOSS OR DAMAGE RESULTING FROM THE USE OF OUR SERVICE OR RELIANCE ON THE INFORMATION PROVIDED THEREIN.
            </p>
          </section>

          <div className="pt-12 text-center">
            <Link to="/dashboard" className="inline-flex items-center gap-3 bg-slate-900 text-white px-10 py-4 rounded-2xl font-bold hover:bg-slate-800 shadow-lg transition-all active:scale-95">
              Return to Dashboard
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
